import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import useSWR from 'swr'
import Pagination from '../components/Pagination';


function fetcher(url: string) {
  return fetch(url).then((res) => res.json());
}

function Home({ items }: any) {
  const [page, setPage] = useState(1);
  const { data } = useSWR(`/api/db?page=${page}`, fetcher);
  console.log(data)
  if (!data) return <div>Loading...</div>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-auto relative">
        <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" className="py-3 px-6">
                ID
              </th>
              <th scope="col" className="py-3 px-6">
                PosterLink
              </th>
              <th scope="col" className="py-3 px-6">
                SeriesTitle
              </th>
              <th scope="col" className="py-3 px-6">
                ReleasedYear
              </th>
              <th scope="col" className="py-3 px-6">
                Certificate
              </th>
              <th scope="col" className="py-3 px-6">
                Runtime
              </th>
              <th scope="col" className="py-3 px-6">
                Genre
              </th>
              <th scope="col" className="py-3 px-6">
                IMDBRating
              </th>
              <th scope="col" className="py-3 px-6">
                Overview
              </th>
              <th scope="col" className="py-3 px-6">
                MetaScore
              </th>
              <th scope="col" className="py-3 px-6">
                Director
              </th>
              <th scope="col" className="py-3 px-6">
                Star1
              </th>
              <th scope="col" className="py-3 px-6">
                Star2
              </th>
              <th scope="col" className="py-3 px-6">
                Star3
              </th>
              <th scope="col" className="py-3 px-6">
                Star4
              </th>
              <th scope="col" className="py-3 px-6">
                NoOfVotes
              </th>
              <th scope="col" className="py-3 px-6">
                Gross
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map((item: any) => (
              <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  {item.id}
                </th>
                <td className="py-4 px-6">
                  <img src={item.PosterLink} height={200} width={200}/>
                </td>
                <td className="py-4 px-6">
                  {item.SeriesTitle}
                </td>
                <td className="py-4 px-6">
                  {item.ReleasedYear}
                </td>
                <td className="py-4 px-6">
                  {item.Certificate}
                </td>
                <td className="py-4 px-6">
                  {item.Runtime}
                </td>
                <td className="py-4 px-6">
                  {item.Genre}
                </td>
                <td className="py-4 px-6">
                  {item.IMDBRating}
                </td>
                <td className="py-4 px-6">
                  {item.Overview}
                </td>
                <td className="py-4 px-6">
                  {item.MetaScore}
                </td>
                <td className="py-4 px-6">
                  {item.Director}
                </td>
                <td className="py-4 px-6">
                  {item.Star1}
                </td>
                <td className="py-4 px-6">
                  {item.Star2}
                </td>
                <td className="py-4 px-6">
                  {item.Star3}
                </td>
                <td className="py-4 px-6">
                  {item.Star4}
                </td>
                <td className="py-4 px-6">
                  {item.NoOfVotes}
                </td>
                <td className="py-4 px-6">
                  {item.Gross}
                </td>
              </tr>
            ))}

          </tbody>
        </table>
      </div>
      <Pagination page={page} setPage={setPage} />
    </>
  )
}


export default Home;